# Generated by Django 3.2 on 2021-05-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donor_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, max_length=15, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('occupation', models.CharField(blank=True, max_length=15, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b', 'B'), ('b-', 'B-'), ('o+', 'O+'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True)),
                ('home_address', models.TextField(blank=True, max_length=50, null=True)),
                ('last_donate_date', models.DateField(blank=True, null=True)),
                ('any_disease', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('allergies', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('cardiac', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('bleeding_disorder', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
                ('hbsAg_hcv_hIV', models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], max_length=4, null=True)),
            ],
        ),
    ]
