# Generated by Django 3.2 on 2021-05-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='con_tact',
        ),
        migrations.RenameModel(
            old_name='search',
            new_name='sea_rch',
        ),
    ]
