# Generated by Django 3.2 on 2021-05-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210510_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor_registration',
            old_name='any_disease',
            new_name='any_diseases',
        ),
        migrations.RenameField(
            model_name='donor_registration',
            old_name='bleeding_disorder',
            new_name='bleeding_disorders',
        ),
        migrations.RemoveField(
            model_name='donor_registration',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donor_registration',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='donor_registration',
            name='state',
        ),
        migrations.AlterField(
            model_name='con_tact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('a+', 'A+'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('o+', 'O+'), ('o-', 'O-'), ('ab+', 'AB+'), ('ab-', 'AB-')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='home_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='last_donate_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='occupation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
