# Generated by Django 3.2 on 2021-11-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20210513_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='con_tact',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donor_registration',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
